spring:
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
  cloud:
    compatibility-verifier:
      enabled: true
    openfeign:
      client:
        config:
          default:
            connectTimeout: 2000
            readTimeout: 5000
            loggerLevel: basic
    loadbalancer:
      health-check:
        refetch-instances: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: when_authorized

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{correlationId:-}]"
